services:
  cnc-be:
    image: cnc-be
    ports:
      - "8080:8080"
    volumes:
      - "./env/.env:/app/.env:ro"
  cnc-fe:
    image: cnc-fe
    ports:
      - "3000:3000"
  db:
    image: postgres
    ports:
      - "5430:5432"
    environment:
      - POSTGRES_PASSWORD=password
